version: "3.1"

services:

    mysql:
        image: "mysql:8.0"
        container_name: app-mysql
        working_dir: /application
        volumes:
            - ./app:/application
        environment:
            MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
            MYSQL_DATABASE: "$MYSQL_DATABASE"
            MYSQL_USER: "$MYSQL_USER"
            MYSQL_PASSWORD: "$MYSQL_PASSWORD"
        ports:
            - "3307:3306"

    php-fpm:
        build:
            dockerfile: Dockerfile
            context: ./docker/php-fpm/
        volumes:
            - ./app:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
        working_dir: /application
        links:
            - mysql

    webserver:
        image: nginx:latest
        container_name: app-webserver
        working_dir: /application
        volumes:
            - ./app:/application
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8001:80"
